Add promtheus metrics for better insight into kube-machine
kube-node/kube-machine pull request #7
Opened 2017-08-11 13:28 UTC by metalmatze

I inlined some global `var`s, I hope that's fine. Otherwise it's pretty straight forward.

2017-08-12 20:10 UTC, guusvw approved these changes

2017-08-31 15:08 UTC, mrIncompetent requested changes

2017-08-31 15:08 UTC, mrIncompetent commented on cmd/controller/main.go
> +	}, []string{"phase"})
Please move the metrics to a separate package

2017-08-31 15:08 UTC, mrIncompetent commented on pkg/controller/node/controller.go
> +		syncSeconds:       syncSeconds,
For simplicity i would rather put them into a separate package with exported functions to interact

2017-08-31 15:08 UTC, mrIncompetent commented on pkg/controller/node/controller.go
> +	}
Please put this into `c.handleErr`

2017-08-31 16:27 UTC, metalmatze commented
There's no real benefit of putting this into a separate package. I'd leave it there. More packages only create more circle dependencies in the future.

2017-09-01 09:51 UTC, mrIncompetent commented
@metalmatze It increases readability & it separates the concerns.

More packages do not create circle dependencies. Bad coding style leads to circle dependencies.

2017-09-23 11:18 UTC, metalmatze commented
Closed & deleted in favor of #19

2017-09-23 11:29 UTC, closed without merging